version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}      # Usuario específico para la aplicación
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  # Contraseña del usuario de aplicación
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  user-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}      # Usa el usuario de aplicación
      DB_PASSWORD: ${MYSQL_PASSWORD}  # en lugar de root
    restart: on-failure
    volumes:
      - .:/app              # Montar el código para desarrollo (opcional)

  user-management-service:
    build: ./user-management-service
    ports:
      - "8006:8006"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}      # Usa el usuario de aplicación
      DB_PASSWORD: ${MYSQL_PASSWORD}  # en lugar de root
    restart: on-failure
    volumes:
      - .:/user-management-service:/app  # Montar el código para desarrollo (opcional) 

  plagiarism-detection-service:
    build: ./plagiarism-detection-service
    ports:
      - "8002:8002"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}      # Usa el usuario de aplicación
      DB_PASSWORD: ${MYSQL_PASSWORD}  # en lugar de root
    restart: on-failure
    volumes:
      - .:/plagiarism-detection-service:/app  # Montar el código para desarrollo (opcional) 

  content-management-service:
    build: ./content-management-service
    ports:
      - "8003:8003"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}      
      DB_PASSWORD: ${MYSQL_PASSWORD}  
    restart: on-failure
    volumes:
      - .:/content-management-service:/app  

  email-notify-service:
    build: ./email-notify-service
    ports:
      - "8004:8004"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}      # Usa el usuario de aplicación
      DB_PASSWORD: ${MYSQL_PASSWORD}  # en lugar de root
    restart: on-failure
    volumes:
      - .:/email-notify-service:/app  # Montar el código para desarrollo (opcional) 

  ai-assistance-service:
    build: ./ai-assistance-service
    ports:
      - "8005:8005"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}      # Usa el usuario de aplicación
      DB_PASSWORD: ${MYSQL_PASSWORD}  # en lugar de root
    restart: on-failure
    volumes:
      - .:/ai-assistance-service:/app  # Montar el código para desarrollo (opcional) 

  api-gateway:
    build: ./api-gateway
    ports:
      - "8010:8010"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      USER_MANAGEMENT_URL: http://user-management-service:8006
      PLAGIARISM_DETECTION_URL: http://plagiarism-detection-service:8002
      EMAIL_NOTIFY_URL: http://email-notify-service:8004
      AI_ASSISTANCE_URL: http://ai-assistance-service:8005

    restart: on-failure
  
volumes:
  mysql_data: