version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  user-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      WAIT_HOSTS: mysql-db:3306  # Espera a que MySQL esté listo

volumes:
  mysql_data: