version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
      MYSQL_USER: app_user      # Usuario específico para la aplicación
      MYSQL_PASSWORD: app_pass  # Contraseña del usuario de aplicación
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  user-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: user_db
      DB_USER: app_user      # Usa el usuario de aplicación
      DB_PASSWORD: app_pass  # en lugar de root
    restart: on-failure
    volumes:
      - .:/app              # Montar el código para desarrollo (opcional)

volumes:
  mysql_data: