"""Prueba2

Revision ID: 8f40236a98a3
Revises: dda0fa8cb1b7
Create Date: 2025-06-08 00:44:12.114093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f40236a98a3'
down_revision: Union[str, None] = 'dda0fa8cb1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=mysql.ENUM('ADMIN', 'INSTRUCTOR', 'STUDENT'),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('ADMIN', 'INSTRUCTOR', 'STUDENT'),
               existing_nullable=False)
    op.create_table('feedback_tasks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id_lab', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id_rep', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_ai', mysql.JSON(), nullable=True),
    sa.Column('feedback_docente', mysql.JSON(), nullable=True),
    sa.Column('n_intentos', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='feedback_tasks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
