"""update with last changes

Revision ID: a447d9569314
Revises: 8f40236a98a3
Create Date: 2025-06-08 01:05:03.445129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a447d9569314'
down_revision: Union[str, None] = '8f40236a98a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_tasks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id_lab', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id_rep', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_ai', mysql.JSON(), nullable=True),
    sa.Column('feedback_docente', mysql.JSON(), nullable=True),
    sa.Column('n_intentos', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='feedback_tasks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
