from sqlalchemy import JSON, Boolean, Column, Integer, Text, String, DateTime, ForeignKey, Float
from sqlalchemy.sql import func
from app.model.base import Base

class Submission(Base):
    __tablename__ = "submissions"

    submission_id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=False)
    code = Column(Text, nullable=False)
    submission_date = Column(DateTime(timezone=True), server_default=func.now())
    result = Column(String(255), nullable=False)
    task_id = Column(Integer, ForeignKey("tasks.id"), nullable=True) 
    code_task_id = Column(Integer, ForeignKey("code_tasks.id"), nullable=True)
    tipo_problema = Column(String(50), nullable=False) # 'task' o 'code_task'
    score = Column(Float, nullable=True)  # ✅ Nuevo campo de puntaje
    number_hints_used = Column(Integer, nullable = False, default = 0)
    test_feedback = Column(JSON, nullable=True)
    status = Column(String(12), nullable=False, default='Sin revisar')
    is_autogenerated = Column(Boolean, default=False)
    autofeedback_id = Column(Integer, nullable=True)