"""Add status field for feedback

Revision ID: 3d0b2e68cb3f
Revises: cae3b93e488e
Create Date: 2025-06-01 01:10:40.822546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0b2e68cb3f'
down_revision: Union[str, None] = 'cae3b93e488e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('status', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'status')
    # ### end Alembic commands ###
