"""Add lines_blocked

Revision ID: e88f1818d13c
Revises: c03c5d56793e
Create Date: 2025-06-13 20:59:27.664900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e88f1818d13c'
down_revision: Union[str, None] = 'c03c5d56793e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('lines_blocked', sa.JSON(), nullable=True))
    op.alter_column('tasks', 'lineas_visibles',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'lineas_visibles',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_column('tasks', 'lines_blocked')
    op.create_table('exams',
    sa.Column('exam_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('time_limit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions', mysql.JSON(), nullable=False),
    sa.Column('settings', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('exam_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_exams_title', 'exams', ['title'], unique=False)
    op.create_table('exam_responses',
    sa.Column('response_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exam_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_responses', mysql.JSON(), nullable=False),
    sa.Column('total_score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], name='exam_responses_ibfk_1'),
    sa.PrimaryKeyConstraint('response_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_exam_responses_exam_id', 'exam_responses', ['exam_id'], unique=False)
    op.create_table('used_hints',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hint_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['hint_id'], ['hints.hint_id'], name='used_hints_ibfk_2'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='used_hints_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_user_task_hint', 'used_hints', ['user_id', 'task_id', 'hint_id'], unique=True)
    op.create_index('ix_used_hints_id', 'used_hints', ['id'], unique=False)
    # ### end Alembic commands ###
